version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: hr-saas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hrsaas
      POSTGRES_PASSWORD: hrsaas123
      POSTGRES_DB: hrsaas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
